name: myenv
channels:
  - conda-forge
dependencies:
  # You need the pangeo-notebook conda-forge package in your environment.yml for compatibility with pangeo cloud deployments
  - pangeo-notebook==2021.09.30
  - xarray
  - hvplot
  - aiohttp
  - dask-ml
  - zarr
  - scikit-learn
  - seaborn
  - tqdm
  - cartopy
  - pip
  - pip:
    - graphviz
    - gitpython
    - cmocean
    - geopandas
    - git+http://github.com/euroargodev/argopy.git@master