# This workflow determines the status of web API used by argopy, every 3 minutes

name: api-status

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/3 * * * *'

jobs:
  api-check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'api-satus'

    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'

#    - name: Install argopy with pip
#      run: |
#        python -m pip install --upgrade pip
#        pip install git+http://github.com/euroargodev/argopy.git@api-status

    - name: Check API status
      run: python -c "import argopy; argopy.utilities.save_api_status()"